package com.travelPlanner.planner.enums;

public enum TripDayWsType {
    ACTIVITY_CREATED,
    ACTIVITY_UPDATED_TITLE,
    ACTIVITY_UPDATED_DESCRIPTION,
    ACTIVITY_UPDATED_START_DATE,
    ACTIVITY_UPDATED_END_DATE,
    ACTIVITY_DELETED,

    ACCOMMODATION_CREATED,
    ACCOMMODATION_UPDATED_NAME,
    ACCOMMODATION_UPDATED_ADDRESS,
    ACCOMMODATION_UPDATED_CHECK_IN,
    ACCOMMODATION_UPDATED_CHECK_OUT,
    ACCOMMODATION_UPDATED_NOTES,
    ACCOMMODATION_DELETED,

    FOOD_CREATED,
    FOOD_UPDATED,
    FOOD_DELETED
}
