# Rename it to application.yml.
# Fill your data where you see "your-...".

spring:
  application:
    name: travel-planner

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: your-issuer-url

  datasource:
    url: jdbc:postgresql://localhost:5432/your-db
    username: your-name
    password: your-password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  port: 8090

cache:
  names:
    trip: tripCache
    day: dayCache
    folder: folderCache

keycloak:
  auth-server-url: yourKeycloakServerUrl
  realm: yourRealmName
  client:
    id: yourClientId
    secret: yourClientSecret

app:
  sync:
    keycloak-batch-size: 100
    db-batch-size: 25
  settings:
    folder:
      max-trips: 10
    app-user:
      max-folders: 5